version: '3.4'

services:
  verify-tests:
    build: .

  selenium-hub:
    image: ghcr.io/alphagov/verify/selenium-hub
    ports:
      - "4444:4444"

  firefoxnode:
    image: ghcr.io/alphagov/verify/selenium-node-firefox
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
    ports:
      - "5555"
    depends_on:
      - selenium-hub
