local:
  frontend: http://localhost:50300
  test-rp: http://localhost:50130/test-rp
  test-rp-entity-id: http://www.test-rp.gov.uk/SAML2/MD
  idps:
    Stub Idp Demo One: http://localhost:50140/stub-idp-demo-one/
    Stub Idp Demo Two: http://localhost:50140/stub-idp-demo-two/
    Stub Idp Disconnected: http://localhost:50140/stub-idp-disconnected/

docker-local:
  frontend: http://frontend
  test-rp: http://test-rp/test-rp
  test-rp-entity-id: http://www.test-rp.gov.uk/SAML2/MD
  idps:
    Stub Idp Demo One: http://stub-idp/stub-idp-demo-one/
    Stub Idp Demo Two: http://stub-idp/stub-idp-demo-two/
    Stub Idp Disconnected: http://stub-idp/stub-idp-disconnected/

staging:
  frontend: https://www.staging.signin.service.gov.uk
  test-rp: https://test-rp-staging.cloudapps.digital/test-rp
  test-rp-entity-id: http://www.staging.test-rp.gov.uk/SAML2/MD
  idps:
    Stub Idp Demo One: https://stub-idp-staging.cloudapps.digital/stub-idp-demo-one/
    Stub Idp Demo Two: https://stub-idp-staging.cloudapps.digital/stub-idp-demo-two/
    Stub Idp Disconnected: https://stub-idp-staging.cloudapps.digital/stub-idp-disconnected/

integration:
  frontend: https://www.integration.signin.service.gov.uk
  test-rp: https://test-rp-integration.cloudapps.digital/test-rp
  test-rp-entity-id: http://www.integration.test-rp.gov.uk/SAML2/MD
  idps:
    Stub Idp Demo Two: https://stub-idp-integration.cloudapps.digital/stub-idp-demo-two/

prod:
  frontend: https://www.signin.service.gov.uk
